//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by HackPro.rc
//
#define IDR_MANIFEST                    1
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_HACKPRO_DIALOG              102
#define START_MENU_SCROLL               102
#define MYCOMPUTER_REMOVE               103
#define RUN_REMOVE                      104
#define DISABLE_RECENT_WMEDIA           105
#define DESKTOP_RIGHTCLICK              106
#define INTERNET_NEWWINDOW              107
#define DESKTOP_CHANGEWALLPOS           108
#define PRIVACY_CLEARPAGEPFILE          109
#define SECURITY_USERTRACKING           110
#define SECURITY_MMCSNAPING             111
#define SECURITY_MMCAUTHORMODE          112
#define HARDWARE_CDAUTORUN              113
#define SECURITY_SECURITYDIALOG         114
#define SECURITY_MESSAGEBLOG            115
#define SECURITY_CHANGEPASSDISABLE      116
#define PRIVACY_LASTUSER                117
#define PRIVACY_HIDEDRIVES              118
#define SOFTAWARE_OPENCMD               119
#define SECURITY_DISABLETASKM           120
#define SECURITY_IMPORTREG              121
#define SECURITY_DISDISPLAY             122
#define IDR_HACKPRO                     123
#define IDR_HTML_WNDLIST                124
#define IDR_HTML_SYNATTACKDLG           125
#define IDR_HTML_SNIFFER                126
#define IDD_MACADD                      129
#define IDD_REGCONFIG                   131
#define IDD_TIP                         132
#define IDD_PORTSCANSIP                 136
#define IDD_DOSSMURF                    137
#define IDI_ICON2                       138
#define IDD_DIALOGRAW                   140
#define IDD_PWD_HASH                    142
#define IDD_ABOUT                       143
#define IDI_ICON3                       148
#define IDI_ICON4                       149
#define IDI_ICON1                       152
#define IDR_MAINFRAME                   152
#define IDI_ICON5                       153
#define IDD_DIALOG1                     154
#define IDD_WNDLSTDLG                   154
#define IDR_MENU1                       158
#define IDR_MENU2                       159
#define IDR_MENU3                       160
#define ID_FILE                         161
#define ID_FILE_CONNECT                 162
#define ID_Menu                         163
#define IDD_GETIP                       164
#define IDD_DLGSYSINFO                  166
#define IDD_DLGSYSCONTROL               167
#define IDD_DESKDLG                     173
#define IDB_BITMAP2                     176
#define IDB_DOS                         176
#define IDD_DIALOG2                     177
#define IDD_PAGEPORTSCAN                177
#define IDD_PORTSCAN                    177
#define IDD_DOSSYN                      178
#define IDD_UDPFLOOD                    179
#define IDB_UDPFLOOD                    182
#define IDB_SYNFLAG                     183
#define IDB_BITMAP3                     186
#define IDD_DIALOG3                     187
#define IDD_PACKETCAP                   187
#define IDD_DIALOG4                     188
#define IDD_NETINFO                     188
#define ID_HELP_ABOUT                   189
#define IDD_NETSTAT                     190
#define IDD_CONNECTIONTABLE             191
#define IDD_VSCAN                       192
#define IDD_REVENGG                     193
#define IDB_BITMAP1                     194
#define ID_OPEN_EXIT                    196
#define ID_Menu197                      197
#define ID_FILE_OPEN198                 198
#define ID_WINDOW_SHOWMAINWINDOW        199
#define ID_WINDOW_ABOUT                 200
#define ID_Menu201                      201
#define IDC_MSTATUS                     1000
#define IDC_MTREE                       1001
#define IDC_MHOLD                       1002
#define IDC_G_LIST                      1005
#define IDC_G_IPADDRESS1                1006
#define IDC_G_IPADDRESS2                1007
#define IDC_G_BUTCOMPARE                1008
#define IDC_G_BUTSAVE                   1009
#define IDC_G_BUTGET                    1010
#define IDC_G_IPADDRESS                 1011
#define IDC_S_MAC                       1013
#define IDC_S_BUTGET                    1014
#define IDC_LIST1                       1017
#define IDC_LIST2                       1018
#define IDC_SPS_BUTSCAN                 1019
#define IDC_LIST3                       1019
#define IDC_EDT_PORT                    1020
#define IDC_LIST5                       1020
#define IDC_SPS_IPADDRESS2              1021
#define IDC_SPS_IPADDRESS1              1022
#define IDC_EDTHKEY                     1024
#define IDC_EDTPATH                     1025
#define IDC_EDTVALNAME                  1026
#define IDC_EDTTYPE                     1027
#define IDC_EDTDATA                     1028
#define IDC_BUTTON1                     1029
#define IDC_BUTTON2                     1030
#define IDC_BUTTON3                     1031
#define IDC_MESSAGE                     1032
#define IDC_BUTTON5                     1032
#define IDC_CAPTION                     1033
#define IDC_BTLOCK                      1033
#define IDC_IPADDRESS1                  1034
#define IDC_BUTTON7                     1034
#define IDC_BUTSCAN                     1035
#define IDC_BUTTON8                     1035
#define IDC_BUTCANCLE                   1036
#define IDC_BUTTON4                     1037
#define IDC_REMOVERNG                   1037
#define IDC_START                       1038
#define IDC_BUTTON6                     1038
#define IDC_IPVICTIM                    1039
#define IDC_BTSETPRTY                   1039
#define IDC_LIST                        1040
#define IDC_BTSETPRTY2                  1040
#define IDC_REFRESH                     1040
#define IDC_IPADDRESS2                  1044
#define IDC_DATA                        1045
#define IDC_PORT                        1046
#define IDC_SRCPORT                     1046
#define IDC_TTL                         1047
#define IDC_IPSRC                       1048
#define IDC_IPDEST                      1049
#define IDC_SEND                        1050
#define IDC_PROTO                       1051
#define IDC_PASSTEXT                    1052
#define IDC_PASSHASH                    1053
#define IDC_LISTHASH                    1054
#define IDC_EXTRHASH                    1055
#define IDC_GETHASH                     1056
#define IDC_ALGORITHM                   1057
#define IDC_ABOUT                       1058
#define IDC_WNDPROPERTY                 1061
#define IDC_WNDLIST                     1062
#define IDC_GETTXT                      1063
#define IDC_TREE1                       1064
#define IDC_MCAPTION                    1066
#define IDC_MCORD_W                     1068
#define IDC_MCORD_C                     1069
#define IDC_MSTYLES                     1070
#define IDC_MEXSTYLE                    1071
#define IDC_MWIDTH                      1073
#define IDC_LIST4                       1081
#define IDC_EDIT2                       1082
#define IDC_FINDTXT                     1082
#define IDC_FILENAME                    1082
#define IDC_EDIT3                       1083
#define IDC_FILENAME2                   1083
#define IDC_EDIT1                       1085
#define IDC_SETCAPTION                  1085
#define IDC_TXTFILE                     1085
#define IDC_NUMOFPACKET                 1085
#define IDC_TXTDATA                     1085
#define IDC_INFOHOSTNAME                1085
#define IDC_TXTFILE2                    1086
#define IDC_INFODOMAINNAME              1086
#define IDC_TXTFILE3                    1087
#define IDC_INFODNSSERVER               1087
#define IDC_EDTINFO                     1088
#define IDC_INFODHCPSNAME               1088
#define IDC_INFOROUTING                 1089
#define IDC_INFODNS                     1090
#define IDC_INFOPROXY                   1091
#define IDC_CMBPRTY                     1092
#define IDC_INFONODETYPE                1092
#define IDC_LSTPROCESS                  1093
#define IDC_BTENDTASK                   1094
#define IDC_BTCLEAR                     1095
#define IDC_BTEXE                       1096
#define IDC_BTSHUTDOWN                  1097
#define IDC_BTLOGOFF                    1098
#define IDC_BTRESTART                   1099
#define IDC_COMBO1                      1100
#define IDC_COMBO2                      1101
#define IDC_GETINFO                     1101
#define IDC_DISP                        1105
#define IDC_BTCONNECT                   1106
#define IDC_BTEXIT                      1107
#define IDC_DESTPORT                    1108
#define IDC_BTABOUT                     1108
#define IDC_DATASIZE                    1109
#define IDC_INFO                        1111
#define IDC_LBLSRCPORT                  1112
#define IDC_LBLDESTPORT                 1113
#define IDC_LBLDATASIZE                 1114
#define IDC_PGRS                        1115
#define IDC_DELAY                       1116
#define IDC_SCANNOW                     1118
#define IDC_EDTPORT                     1119
#define IDC_EDTPORT1                    1119
#define IDC_EDTPORT2                    1120
#define IDC_PROGRESS1                   1120
#define IDC_PROGRESS                    1120
#define IDC_NUMBEROFPACKETS             1121
#define IDC_IP2                         1122
#define IDC_NUMOFPACKETS                1124
#define IDC_VICTIMPORT                  1125
#define IDC_IP1                         1126
#define IDC_BTFINDWINDOW                1127
#define IDC_FRAME                       1128
#define IDC_BTSTART                     1129
#define IDC_DETAIL                      1130
#define IDC_SEQ                         1131
#define IDC_TCPFLAG                     1132
#define IDC_DATAOFFSET                  1133
#define IDC_ICMPTYPE                    1134
#define IDC_LSTCAP                      1135
#define IDC_CLEAR                       1136
#define IDC_REFRESHTABLE                1137
#define IDC_IPLIST                      1138
#define IDC_LSTEVENT                    1139
#define IDC_BTEXECUTE                   1140
#define IDC_BRWS                        1141
#define IDC_OUT1                        1142
#define IDC_BRWS2                       1142
#define IDC_OUT2                        1143
#define IDC_OUT3                        1144
#define IDC_RADIO1                      1145
#define IDC_RNEW                        1145
#define IDC_RADIO2                      1146
#define IDC_RRUN                        1146
#define IDC_EDIT4                       1147
#define IDC_DLLPATH                     1147
#define IDC_PNEW                        1148
#define IDC_POLD                        1149
#define IDC_BTREFRESH                   1150
#define IDC_EDTPID                      1151
#define IDC_TERMINATE                   1152

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        202
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1153
#define _APS_NEXT_SYMED_VALUE           127
#endif
#endif
